"use client";

import {useState} from "react";

const copies={
  it:{summary:"Proposta",stay:"Soggiorno",guests:"Ospiti",total:"Totale",deposit:"Acconto richiesto",method:"Metodo di pagamento",bank:"Bonifico bancario",paypal:"PayPal",date:"Data del pagamento",amount:"Importo versato (€)",reference:"Riferimento operazione",referenceHint:"CRO, TRN o identificativo PayPal, se disponibile",message:"Messaggio",receipt:"Ricevuta (facoltativa)",receiptHint:"PDF, JPG o PNG · massimo 5 MB. Oscura saldo e movimenti non pertinenti.",submit:"Comunica il pagamento",sending:"Invio in corso…",success:"Pagamento comunicato",successBody:"Grazie. Verificheremo l’accredito e ti invieremo la conferma scritta della prenotazione.",error:"Non è stato possibile registrare il pagamento. Riprova oppure rispondi all’email ricevuta."},
  en:{summary:"Proposal",stay:"Stay",guests:"Guests",total:"Total",deposit:"Required advance",method:"Payment method",bank:"Bank transfer",paypal:"PayPal",date:"Payment date",amount:"Amount paid (€)",reference:"Transaction reference",referenceHint:"CRO, TRN or PayPal transaction ID, if available",message:"Message",receipt:"Receipt (optional)",receiptHint:"PDF, JPG or PNG · maximum 5 MB. Hide unrelated balances and transactions.",submit:"Notify payment",sending:"Sending…",success:"Payment reported",successBody:"Thank you. We will verify the payment and send your written booking confirmation.",error:"We could not record the payment. Please try again or reply to the email you received."},
  fr:{summary:"Proposition",stay:"Séjour",guests:"Voyageurs",total:"Total",deposit:"Acompte demandé",method:"Mode de paiement",bank:"Virement bancaire",paypal:"PayPal",date:"Date du paiement",amount:"Montant versé (€)",reference:"Référence de l’opération",referenceHint:"CRO, TRN ou identifiant PayPal, si disponible",message:"Message",receipt:"Reçu (facultatif)",receiptHint:"PDF, JPG ou PNG · 5 Mo maximum. Masquez les soldes et opérations sans rapport.",submit:"Signaler le paiement",sending:"Envoi…",success:"Paiement signalé",successBody:"Merci. Nous vérifierons le paiement et vous enverrons la confirmation écrite de la réservation.",error:"Le paiement n’a pas pu être enregistré. Réessayez ou répondez à l’e-mail reçu."},
  es:{summary:"Propuesta",stay:"Estancia",guests:"Huéspedes",total:"Total",deposit:"Anticipo solicitado",method:"Método de pago",bank:"Transferencia bancaria",paypal:"PayPal",date:"Fecha del pago",amount:"Importe pagado (€)",reference:"Referencia de la operación",referenceHint:"CRO, TRN o identificador PayPal, si está disponible",message:"Mensaje",receipt:"Recibo (opcional)",receiptHint:"PDF, JPG o PNG · máximo 5 MB. Oculta saldos y movimientos no relacionados.",submit:"Comunicar el pago",sending:"Enviando…",success:"Pago comunicado",successBody:"Gracias. Verificaremos el pago y enviaremos la confirmación escrita de la reserva.",error:"No se pudo registrar el pago. Inténtalo de nuevo o responde al correo recibido."},
  de:{summary:"Angebot",stay:"Aufenthalt",guests:"Gäste",total:"Gesamt",deposit:"Erforderliche Anzahlung",method:"Zahlungsart",bank:"Banküberweisung",paypal:"PayPal",date:"Zahlungsdatum",amount:"Gezahlter Betrag (€)",reference:"Transaktionsreferenz",referenceHint:"CRO, TRN oder PayPal-ID, falls vorhanden",message:"Nachricht",receipt:"Beleg (optional)",receiptHint:"PDF, JPG oder PNG · maximal 5 MB. Blenden Sie nicht relevante Kontostände und Umsätze aus.",submit:"Zahlung mitteilen",sending:"Wird gesendet…",success:"Zahlung mitgeteilt",successBody:"Vielen Dank. Wir prüfen den Zahlungseingang und senden Ihnen die schriftliche Buchungsbestätigung.",error:"Die Zahlung konnte nicht gespeichert werden. Versuchen Sie es erneut oder antworten Sie auf die erhaltene E-Mail."},
};

export default function PaymentForm({token,language,guestName,arrival,departure,guests,totalCents}:{token:string;language:string;guestName:string;arrival:string;departure:string;guests:number;totalCents:number}){
  const copy=copies[language as keyof typeof copies]||copies.it;
  const locale=({it:"it-IT",en:"en-GB",fr:"fr-FR",es:"es-ES",de:"de-DE"} as Record<string,string>)[language]||"it-IT";
  const money=(cents:number)=>new Intl.NumberFormat(locale,{style:"currency",currency:"EUR"}).format(cents/100);
  const [state,setState]=useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();
    setState("sending");
    try{
      const form=new FormData(event.currentTarget);
      const response=await fetch(`/api/pagamento/${token}`,{method:"POST",body:form});
      setState(response.ok?"success":"error");
    }catch{setState("error");}
  }
  if(state==="success")return <section className="payment-success"><span>✓</span><h2>{copy.success}</h2><p>{copy.successBody}</p></section>;
  return <section className="payment-shell"><aside><p className="eyebrow">{copy.summary}</p><h2>{guestName}</h2><dl><div><dt>{copy.stay}</dt><dd>{arrival} – {departure}</dd></div><div><dt>{copy.guests}</dt><dd>{guests}</dd></div><div><dt>{copy.total}</dt><dd>{money(totalCents)}</dd></div><div><dt>{copy.deposit}</dt><dd>{money(Math.round(totalCents*.3))}</dd></div></dl></aside><form className="payment-form" onSubmit={submit}><fieldset><legend>{copy.method}</legend><div className="payment-methods"><label><input type="radio" name="method" value="bank_transfer" defaultChecked required/>{copy.bank}</label><label><input type="radio" name="method" value="paypal" required/>{copy.paypal}</label></div></fieldset><div className="payment-grid"><label>{copy.date}<input type="date" name="paidAt" max={new Date().toISOString().slice(0,10)} required/></label><label>{copy.amount}<input type="text" name="amount" inputMode="decimal" defaultValue={(Math.round(totalCents*.3)/100).toFixed(2).replace(".",",")} required/></label><label className="field-wide">{copy.reference}<span>{copy.referenceHint}</span><input type="text" name="reference" maxLength={120}/></label><label className="field-wide">{copy.message}<textarea name="message" rows={4} maxLength={2000}/></label><label className="field-wide payment-file">{copy.receipt}<span>{copy.receiptHint}</span><input type="file" name="receipt" accept="application/pdf,image/jpeg,image/png"/></label></div>{state==="error"&&<p className="form-error" role="alert">{copy.error}</p>}<button className="button" disabled={state==="sending"}>{state==="sending"?copy.sending:copy.submit}</button></form></section>;
}
