"use client";

import { FormEvent, useState } from "react";

type Lang = "it" | "en" | "fr" | "es" | "de";

const copy = {
  it: { nav:["La Suite","Servizi","Galleria","Dintorni","Prenota","Contatti"], hero:"La tua casa tra Liguria e Toscana", heroText:"Casa vacanze indipendente ad Arcola, punto di partenza ideale per Cinque Terre, Lerici, Portovenere, Sarzana e la costa toscana.", discover:"Scopri la Suite", availability:"Verifica disponibilità", welcome:"Il piacere di una casa tutta per voi", welcomeText:"VALF Suite è una casa vacanze indipendente ad Arcola, tra le colline della Val di Magra e a pochi minuti dal mare. Spazi curati, essenziali e accoglienti, pensati per chi cerca tranquillità senza rinunciare alla comodità.", strategic:"Una posizione strategica, tra mare e borghi", suiteTitle:"Un monolocale indipendente fino a 4 ospiti", suiteText:"VALF Suite è al piano terra. L’ambiente principale dispone di un letto in zona appartata e di un divano letto; un soppalco, alto 153 cm, ospita un ulteriore posto letto. Completano la casa un angolo cottura attrezzato, climatizzazione, TV, area esterna privata e parcheggio.", servicesTitle:"Tutto il necessario per un soggiorno comodo", galleryTitle:"Uno sguardo alla casa", galleryText:"Le fotografie definitive degli spazi interni e dell’area esterna saranno pubblicate a breve. Nel frattempo puoi contattarci per maggiori informazioni.", areaTitle:"Cosa vedere nei dintorni", areaText:"Mare, borghi storici e città d’arte sono raggiungibili in auto o con i mezzi pubblici. La stazione di Arcola è sulla linea Genova–Pisa; La Spezia Centrale è il nodo per il Cinque Terre Express.", bookTitle:"Richiedi disponibilità", bookText:"Seleziona le date e invia la richiesta: Angela ti risponderà personalmente per confermare disponibilità e condizioni.", contactsTitle:"Contatti", contactsText:"Per informazioni e richieste di soggiorno siamo a tua disposizione.", termsTitle:"Condizioni di prenotazione e cancellazione", send:"Invia la richiesta", privacy:"Accetto il trattamento dei dati per questa richiesta." },
  en: { nav:["The Suite","Amenities","Gallery","The Area","Book","Contact"], hero:"Your home between Liguria and Tuscany", heroText:"An independent holiday home in Arcola, an ideal base for the Cinque Terre, Lerici, Portovenere, Sarzana and the Tuscan coast.", discover:"Discover the Suite", availability:"Check availability", welcome:"The pleasure of a home all to yourself", welcomeText:"VALF Suite is an independent holiday home in Arcola, between the Val di Magra hills and the sea. Welcoming, carefully designed spaces for travellers seeking peace and convenience.", strategic:"A strategic location between sea and villages", suiteTitle:"An independent studio for up to 4 guests", suiteText:"VALF Suite is on the ground floor. It includes a secluded bed area, a sofa bed and a mezzanine, 153 cm high, with an additional bed. There is also an equipped kitchenette, air conditioning, TV, private outdoor area and parking.", servicesTitle:"Everything you need for a comfortable stay", galleryTitle:"A look inside the house", galleryText:"Final photographs of the interiors and outdoor area will be published soon. Contact us in the meantime for more information.", areaTitle:"Explore the surrounding area", areaText:"The sea, historic villages and art cities can be reached by car or public transport. Arcola station is on the Genoa–Pisa line; La Spezia Centrale is the gateway to the Cinque Terre Express.", bookTitle:"Request availability", bookText:"Select your dates and send a request. Angela will reply personally with availability and conditions.", contactsTitle:"Contact", contactsText:"We are available for information and stay requests.", termsTitle:"Booking and cancellation terms", send:"Send request", privacy:"I agree to the processing of my data for this request." },
  fr: { nav:["La Suite","Services","Galerie","Les environs","Réserver","Contact"], hero:"Votre maison entre la Ligurie et la Toscane", heroText:"Une maison de vacances indépendante à Arcola, point de départ idéal pour les Cinque Terre, Lerici, Portovenere, Sarzana et la côte toscane.", discover:"Découvrir la Suite", availability:"Vérifier les disponibilités", welcome:"Le plaisir d’une maison rien que pour vous", welcomeText:"VALF Suite est une maison de vacances indépendante à Arcola, entre les collines du Val di Magra et la mer. Des espaces accueillants et soignés pour un séjour paisible et pratique.", strategic:"Une position stratégique entre mer et villages", suiteTitle:"Un studio indépendant jusqu’à 4 personnes", suiteText:"VALF Suite se trouve au rez-de-chaussée. Elle comprend un lit dans un espace réservé, un canapé-lit et une mezzanine de 153 cm de haut avec un couchage supplémentaire, ainsi qu’une kitchenette, la climatisation, la télévision, un espace extérieur privé et un parking.", servicesTitle:"Tout le nécessaire pour un séjour confortable", galleryTitle:"Un aperçu de la maison", galleryText:"Les photos définitives des intérieurs et de l’espace extérieur seront bientôt publiées. Contactez-nous pour plus d’informations.", areaTitle:"Découvrir les environs", areaText:"Mer, villages historiques et villes d’art sont accessibles en voiture ou en transports publics. La gare d’Arcola se trouve sur la ligne Gênes–Pise; La Spezia Centrale dessert les Cinque Terre.", bookTitle:"Demander les disponibilités", bookText:"Sélectionnez vos dates et envoyez une demande. Angela vous répondra personnellement.", contactsTitle:"Contact", contactsText:"Nous sommes à votre disposition pour toute information.", termsTitle:"Conditions de réservation et d’annulation", send:"Envoyer la demande", privacy:"J’accepte le traitement de mes données pour cette demande." },
  es: { nav:["La Suite","Servicios","Galería","Alrededores","Reservar","Contacto"], hero:"Tu casa entre Liguria y Toscana", heroText:"Una casa de vacaciones independiente en Arcola, punto de partida ideal para Cinque Terre, Lerici, Portovenere, Sarzana y la costa toscana.", discover:"Descubre la Suite", availability:"Consultar disponibilidad", welcome:"El placer de una casa solo para vosotros", welcomeText:"VALF Suite es una casa de vacaciones independiente en Arcola, entre las colinas del Val di Magra y el mar. Espacios cuidados y acogedores para disfrutar de tranquilidad y comodidad.", strategic:"Una ubicación estratégica entre mar y pueblos", suiteTitle:"Un estudio independiente para hasta 4 huéspedes", suiteText:"VALF Suite está en la planta baja. Dispone de una cama en una zona apartada, sofá cama y un altillo de 153 cm de altura con una cama adicional, además de cocina, climatización, TV, zona exterior privada y aparcamiento.", servicesTitle:"Todo lo necesario para una estancia cómoda", galleryTitle:"Una mirada a la casa", galleryText:"Pronto publicaremos las fotografías definitivas del interior y de la zona exterior. Contáctanos para más información.", areaTitle:"Qué ver en los alrededores", areaText:"El mar, los pueblos históricos y las ciudades de arte son accesibles en coche o transporte público. La estación de Arcola está en la línea Génova–Pisa; La Spezia Centrale conecta con Cinque Terre.", bookTitle:"Solicitar disponibilidad", bookText:"Selecciona las fechas y envía una solicitud. Angela responderá personalmente.", contactsTitle:"Contacto", contactsText:"Estamos disponibles para información y solicitudes.", termsTitle:"Condiciones de reserva y cancelación", send:"Enviar solicitud", privacy:"Acepto el tratamiento de mis datos para esta solicitud." },
  de: { nav:["Die Suite","Ausstattung","Galerie","Umgebung","Buchen","Kontakt"], hero:"Ihr Zuhause zwischen Ligurien und der Toskana", heroText:"Ein unabhängiges Ferienhaus in Arcola – idealer Ausgangspunkt für Cinque Terre, Lerici, Portovenere, Sarzana und die toskanische Küste.", discover:"Die Suite entdecken", availability:"Verfügbarkeit prüfen", welcome:"Ein Ferienhaus ganz für Sie", welcomeText:"VALF Suite ist ein unabhängiges Ferienhaus in Arcola, zwischen den Hügeln des Val di Magra und dem Meer. Gepflegte, einladende Räume für Ruhe und Komfort.", strategic:"Strategisch gelegen zwischen Meer und Dörfern", suiteTitle:"Ein unabhängiges Studio für bis zu 4 Gäste", suiteText:"VALF Suite liegt im Erdgeschoss. Sie verfügt über einen abgetrennten Schlafbereich, ein Schlafsofa und eine 153 cm hohe Galerie mit zusätzlichem Bett sowie Küchenzeile, Klimaanlage, TV, privaten Außenbereich und Parkplatz.", servicesTitle:"Alles für einen komfortablen Aufenthalt", galleryTitle:"Ein Blick ins Haus", galleryText:"Die endgültigen Fotos der Innenräume und des Außenbereichs werden bald veröffentlicht. Kontaktieren Sie uns für weitere Informationen.", areaTitle:"Die Umgebung entdecken", areaText:"Meer, historische Dörfer und Kunststädte sind mit Auto oder öffentlichen Verkehrsmitteln erreichbar. Der Bahnhof Arcola liegt an der Strecke Genua–Pisa; La Spezia Centrale ist der Ausgangspunkt für Cinque Terre.", bookTitle:"Verfügbarkeit anfragen", bookText:"Wählen Sie Ihre Daten und senden Sie eine Anfrage. Angela antwortet Ihnen persönlich.", contactsTitle:"Kontakt", contactsText:"Für Informationen und Aufenthaltsanfragen sind wir gerne da.", termsTitle:"Buchungs- und Stornierungsbedingungen", send:"Anfrage senden", privacy:"Ich stimme der Verarbeitung meiner Daten für diese Anfrage zu." }
} satisfies Record<Lang, Record<string, string | string[]>>;

const routes = ["la-suite","servizi","galleria","dintorni","prenota","contatti"];
const reservedAreaLabels: Record<Lang,string> = { it:"Area riservata", en:"Reserved area", fr:"Espace réservé", es:"Área reservada", de:"Geschützter Bereich" };
const serviceItems:Record<Lang,string[]> = {
  it:["Wi‑Fi gratuito","Climatizzatore caldo/freddo","Angolo cottura attrezzato","TV","Parcheggio privato","Area esterna privata","Piano terra","Biancheria e asciugamani inclusi"],
  en:["Free Wi‑Fi","Heating and air conditioning","Equipped kitchenette","TV","Private parking","Private outdoor area","Ground floor","Bed linen and towels included"],
  fr:["Wi‑Fi gratuit","Climatisation chaud/froid","Kitchenette équipée","Télévision","Parking privé","Espace extérieur privé","Rez-de-chaussée","Linge de lit et serviettes inclus"],
  es:["Wi‑Fi gratuito","Climatización frío/calor","Cocina equipada","Televisión","Aparcamiento privado","Zona exterior privada","Planta baja","Ropa de cama y toallas incluidas"],
  de:["Kostenloses WLAN","Klimaanlage warm/kalt","Ausgestattete Küchenzeile","TV","Privatparkplatz","Privater Außenbereich","Erdgeschoss","Bettwäsche und Handtücher inklusive"]
};
const places = [
  ["Cinque Terre","40 min in auto · consigliato il treno da La Spezia","5-terre.webp"],
  ["Lerici e San Terenzo","20 min · castello, spiagge e Golfo dei Poeti","lerici.webp"],
  ["Tellaro","25 min · borgo di pescatori sul mare","tellaro.webp"],
  ["Portovenere","30 min · San Pietro e isola Palmaria","portovenere.webp"],
  ["Sarzana","10–15 min · centro storico e fortezze","Sarzana.webp"],
  ["Lunigiana","20–40 min · castelli, borghi e natura","stretti-di-giaredo-3.webp"],
  ["Viareggio e Versilia","45 min · spiagge e architettura liberty","versilia.webp"],
  ["Pisa","circa 1 ora · Piazza dei Miracoli","pisa.webp"]
];
const labels:Record<Lang,{contact:string[];form:string[];notice:string;details:string[];terms:[string,string][]}> = {
  it:{contact:["Referente","Telefono e WhatsApp","Email","Indirizzo"],form:["Arrivo","Partenza","Ospiti","Nome","Email","Messaggio"],notice:"Capienza massima: 4 ospiti · Non sono ammessi animali · Non è consentito fumare all’interno.",details:["Fino a 4 ospiti","Monolocale indipendente al piano terra","Letto in zona appartata e divano letto","Soppalco con posto letto aggiuntivo (altezza 153 cm)","Angolo cottura attrezzato","Area esterna e parcheggio privato"],terms:[["Prenotazione e pagamento","La prenotazione si conferma con un acconto del 30%. Il saldo è dovuto 7 giorni prima dell’arrivo."],["Cancellazione","Rimborso completo fino a 7 giorni prima dell’arrivo. Oltre tale termine l’importo versato non è rimborsabile."],["Check-in e check-out","Gli orari sono flessibili e concordati direttamente con gli ospiti."],["Regole della casa","Massimo 4 ospiti. Non sono ammessi animali, fumo all’interno, feste o eventi."]]},
  en:{contact:["Contact person","Phone and WhatsApp","Email","Address"],form:["Arrival","Departure","Guests","Name","Email","Message"],notice:"Maximum 4 guests · No pets · No smoking indoors.",details:["Up to 4 guests","Independent ground-floor studio","Secluded bed area and sofa bed","Mezzanine with additional bed (153 cm high)","Equipped kitchenette","Private outdoor area and parking"],terms:[["Booking and payment","A 30% deposit confirms the booking. The balance is due 7 days before arrival."],["Cancellation","Full refund up to 7 days before arrival. After that date, payments are non-refundable."],["Check-in and check-out","Times are flexible and agreed directly with guests."],["House rules","Maximum 4 guests. No pets, indoor smoking, parties or events."]]},
  fr:{contact:["Contact","Téléphone et WhatsApp","E-mail","Adresse"],form:["Arrivée","Départ","Personnes","Nom","E-mail","Message"],notice:"Maximum 4 personnes · Animaux non admis · Il est interdit de fumer à l’intérieur.",details:["Jusqu’à 4 personnes","Studio indépendant au rez-de-chaussée","Espace lit séparé et canapé-lit","Mezzanine avec couchage supplémentaire (hauteur 153 cm)","Kitchenette équipée","Espace extérieur privé et parking"],terms:[["Réservation et paiement","La réservation est confirmée par un acompte de 30 %. Le solde est dû 7 jours avant l’arrivée."],["Annulation","Remboursement intégral jusqu’à 7 jours avant l’arrivée. Ensuite, les sommes versées ne sont pas remboursables."],["Arrivée et départ","Les horaires sont flexibles et convenus directement avec les hôtes."],["Règles de la maison","Maximum 4 personnes. Animaux, tabac à l’intérieur, fêtes et événements interdits."]]},
  es:{contact:["Persona de contacto","Teléfono y WhatsApp","Correo electrónico","Dirección"],form:["Llegada","Salida","Huéspedes","Nombre","Correo electrónico","Mensaje"],notice:"Máximo 4 huéspedes · No se admiten animales · No se permite fumar en el interior.",details:["Hasta 4 huéspedes","Estudio independiente en planta baja","Zona de cama apartada y sofá cama","Altillo con cama adicional (altura 153 cm)","Cocina equipada","Zona exterior privada y aparcamiento"],terms:[["Reserva y pago","La reserva se confirma con un depósito del 30 %. El saldo se abona 7 días antes de la llegada."],["Cancelación","Reembolso completo hasta 7 días antes de la llegada. Después, los importes abonados no son reembolsables."],["Llegada y salida","Los horarios son flexibles y se acuerdan directamente con los huéspedes."],["Normas de la casa","Máximo 4 huéspedes. No se admiten animales, tabaco en el interior, fiestas ni eventos."]]},
  de:{contact:["Ansprechpartnerin","Telefon und WhatsApp","E-Mail","Adresse"],form:["Anreise","Abreise","Gäste","Name","E-Mail","Nachricht"],notice:"Maximal 4 Gäste · Keine Haustiere · Rauchen im Innenbereich nicht gestattet.",details:["Bis zu 4 Gäste","Unabhängiges Studio im Erdgeschoss","Abgetrennter Schlafbereich und Schlafsofa","Galerie mit Zusatzbett (153 cm hoch)","Ausgestattete Küchenzeile","Privater Außenbereich und Parkplatz"],terms:[["Buchung und Zahlung","Die Buchung wird mit einer Anzahlung von 30 % bestätigt. Der Restbetrag ist 7 Tage vor Anreise fällig."],["Stornierung","Volle Erstattung bis 7 Tage vor Anreise. Danach sind Zahlungen nicht erstattungsfähig."],["Check-in und Check-out","Die Zeiten sind flexibel und werden direkt mit den Gästen vereinbart."],["Hausregeln","Maximal 4 Gäste. Keine Haustiere, Rauchen im Innenbereich, Partys oder Veranstaltungen."]]}
};

export function SitePage({ lang: langValue, page }: { lang: string; page: string }) {
  const lang = (langValue in copy ? langValue : "it") as Lang;
  const t = copy[lang];
  const [open,setOpen] = useState(false); const [status,setStatus] = useState("");
  const base = lang === "it" ? "" : `/${lang}`;
  const href = (route:string) => `${base}/${route}`;
  async function submit(e:FormEvent<HTMLFormElement>){ e.preventDefault(); setStatus("…"); const f=e.currentTarget; const payload={...Object.fromEntries(new FormData(f)),lingua:lang}; const r=await fetch("/api/disponibilita",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const j=await r.json().catch(()=>({})); setStatus(r.ok?`✓ ${j.message||"Richiesta ricevuta"}`:(j.message||"Invio non disponibile")); if(r.ok)f.reset(); }
  return <main>
    <header className="site-header"><a className="brand" href={base||"/"}><img src="/logo-valf-suite.png" alt="VALF Suite"/></a><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}><span className="sr-only">Menu</span><span/><span/></button><nav className={open?"nav open":"nav"}>{routes.map((r,i)=><a key={r} className={r==="prenota"?"nav-cta":""} href={href(r)}>{(t.nav as string[])[i]}</a>)}</nav></header>
    <div className="language-bar" aria-label="Lingue">{(["it","en","fr","es","de"] as Lang[]).map(l=><a key={l} className={l===lang?"active":""} aria-current={l===lang?"page":undefined} href={l==="it"?`/${page==="home"?"":page}`:`/${l}/${page==="home"?"":page}`}>{l.toUpperCase()}</a>)}</div>
    {page==="home" && <><section className="hero"><div className="hero-copy"><p className="eyebrow">Casa vacanze · Arcola (SP)</p><h1>{t.hero as string}</h1><p className="lead">{t.heroText as string}</p><div className="hero-actions"><a className="button" href={href("prenota")}>{t.availability as string}</a><a className="text-link" href={href("la-suite")}>{t.discover as string} →</a></div></div><div className="hero-art"><div className="sun"/><div className="coast coast-one"/><div className="coast coast-two"/><p>VALF Suite<br/>Arcola · Liguria</p></div></section><section className="intro section"><div><p className="eyebrow">VALF Suite</p><h2>{t.welcome as string}</h2></div><div className="intro-text"><p>{t.welcomeText as string}</p></div></section><section className="services section"><div className="section-heading"><p className="eyebrow">Liguria & Toscana</p><h2>{t.strategic as string}</h2></div><div className="destination-grid home-destinations">{places.slice(0,6).map(([p,d])=><article key={p}><h3>{p}</h3><p>{d}</p></article>)}</div></section><section className="home-links">{routes.slice(0,4).map((r,i)=><a key={r} href={href(r)}><span>0{i+1}</span><strong>{(t.nav as string[])[i]}</strong><b>→</b></a>)}</section></>}
    {page==="la-suite" && <Info title={t.suiteTitle as string} eyebrow={(t.nav as string[])[0]} intro={t.suiteText as string}><ul className="detail-list">{labels[lang].details.map(x=><li key={x}>{x}</li>)}</ul></Info>}
    {page==="servizi" && <Info title={t.servicesTitle as string} eyebrow={(t.nav as string[])[1]} intro=""><div className="amenities">{serviceItems[lang].map((s,i)=><article key={s}><span>0{i+1}</span><h3>{s}</h3></article>)}</div><p className="notice">{labels[lang].notice}</p></Info>}
    {page==="galleria" && <Info title={t.galleryTitle as string} eyebrow={(t.nav as string[])[2]} intro={t.galleryText as string}><div className="gallery-grid">{["Zona giorno","Zona notte","Cucina","Soppalco","Area esterna","Dettagli"].map((x,i)=><div key={x} className={`photo-placeholder ${i===0?"wide":""}`}><span>{x}</span></div>)}</div></Info>}
    {page==="dintorni" && <Info title={t.areaTitle as string} eyebrow={(t.nav as string[])[3]} intro={t.areaText as string}><div className="places-list">{places.map(([p,d,img],i)=><article key={p}><img src={`/dintorni/${img}`} alt={p}/><span>0{i+1}</span><div><h3>{p}</h3><p>{d}</p></div></article>)}</div></Info>}
    {page==="prenota" && <Info title={t.bookTitle as string} eyebrow={(t.nav as string[])[4]} intro={t.bookText as string}><Availability onSubmit={submit} t={t} status={status} labels={labels[lang].form}/></Info>}
    {page==="contatti" && <Info title={t.contactsTitle as string} eyebrow={(t.nav as string[])[5]} intro={t.contactsText as string}><div className="contact-card"><p><small>{labels[lang].contact[0]}</small><strong>Angela</strong></p><p><small>{labels[lang].contact[1]}</small><a className="contact-link" href="tel:+393403726198">+39 340 372 6198</a></p><p><small>{labels[lang].contact[2]}</small><a className="contact-link" href="mailto:valfsuite@gmail.com">valfsuite@gmail.com</a></p><p><small>{labels[lang].contact[3]}</small><span>Via Aurelia Nord 97, 19021 Arcola (SP)</span></p></div></Info>}
    {page==="condizioni" && <Info title={t.termsTitle as string} eyebrow="VALF Suite" intro=""><div className="terms">{labels[lang].terms.map(([h,p])=><section key={h}><h3>{h}</h3><p>{p}</p></section>)}</div></Info>}
    <footer><a className="brand footer-brand" href={base||"/"}><img src="/logo-valf-suite.png" alt="VALF Suite"/></a><p>Via Aurelia Nord 97 · Arcola (SP)</p><div><a href={href("condizioni")}>{t.termsTitle as string}</a><a href={href("contatti")}>{t.contactsTitle as string}</a><a href="/area-riservata" rel="nofollow">{reservedAreaLabels[lang]}</a></div><small>© {new Date().getFullYear()} VALF Suite</small></footer>
  </main>
}

function Info({title,eyebrow,intro,children}:{title:string;eyebrow:string;intro:string;children:React.ReactNode}){return <><section className="page-hero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{intro&&<p className="lead">{intro}</p>}</section><section className="page-body">{children}</section></>}
function Availability({onSubmit,t,status,labels:l}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;t:Record<string,string|string[]>;status:string;labels:string[]}){const today=localIsoDate(new Date());return <form className="availability-form" onSubmit={onSubmit}><div className="form-row"><label>{l[0]}<input name="arrivo" type="date" min={today} required/></label><label>{l[1]}<input name="partenza" type="date" min={today} required/></label></div><div className="form-row"><label>{l[2]}<select name="ospiti" required defaultValue=""><option value="" disabled>—</option>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label><label>{l[3]}<input name="nome" maxLength={120} required/></label></div><label>{l[4]}<input name="email" type="email" maxLength={254} required/></label><label>{l[5]}<textarea name="messaggio" maxLength={2000} rows={4}/></label><label className="form-trap" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="privacy"><input name="privacy" type="checkbox" required/><span>{t.privacy as string}</span></label><button className="button submit">{t.send as string}</button><p className="form-status" role="status">{status}</p></form>}

function localIsoDate(date:Date){const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,"0");const d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`;}
