"use client";

import { FormEvent, useState } from "react";

type Lang = "it" | "en" | "fr" | "es" | "de";

const copy = {
  it: { nav:["La Suite","Servizi","Galleria","Dintorni","Prenota","Contatti"], hero:"La tua casa tra Liguria e Toscana", heroText:"VALF Suite è un appartamento indipendente ad Arcola, al piano terra, con parcheggio privato, Wi‑Fi e climatizzazione. Una base comoda per scoprire Lerici, Portovenere, le Cinque Terre, Sarzana e la costa toscana.", discover:"Scopri la Suite", availability:"Verifica disponibilità", welcome:"Il piacere di uno spazio tutto per voi", welcomeText:"Spazi curati, essenziali e accoglienti, pensati per chi cerca tranquillità, autonomia e una posizione comoda tra il mare e i borghi.", strategic:"Una posizione strategica, tra mare e borghi", suiteTitle:"Un appartamento indipendente fino a 4 ospiti", suiteText:"VALF Suite è un appartamento accogliente e indipendente, pensato per offrire comfort e libertà durante il soggiorno.", servicesTitle:"Tutto il necessario per un soggiorno comodo", galleryTitle:"Uno sguardo alla casa", galleryText:"Le fotografie definitive degli spazi interni e dell’area esterna saranno pubblicate a breve. Nel frattempo puoi contattarci per maggiori informazioni.", areaTitle:"Cosa vedere nei dintorni", areaText:"Mare, borghi storici e città d’arte sono raggiungibili in auto o con i mezzi pubblici. La stazione di Arcola è sulla linea Genova–Pisa; La Spezia Centrale è il nodo per il Cinque Terre Express.", bookTitle:"Richiedi disponibilità", bookText:"Seleziona le date e invia la richiesta: Angela ti risponderà personalmente per confermare disponibilità e condizioni.", contactsTitle:"Contatti", contactsText:"Per informazioni e richieste di soggiorno siamo a tua disposizione.", termsTitle:"Condizioni di prenotazione e cancellazione", send:"Invia la richiesta", privacy:"Accetto il trattamento dei dati per questa richiesta." },
  en: { nav:["The Suite","Amenities","Gallery","The Area","Book","Contact"], hero:"Your home between Liguria and Tuscany", heroText:"VALF Suite is an independent ground-floor apartment in Arcola, with private parking, Wi‑Fi and air conditioning. A convenient base for Lerici, Portovenere, the Cinque Terre, Sarzana and the Tuscan coast.", discover:"Discover the Suite", availability:"Check availability", welcome:"The pleasure of a place all to yourself", welcomeText:"Refined, welcoming spaces designed for guests looking for peace, independence and a convenient location between the coast and historic villages.", strategic:"A strategic location between sea and villages", suiteTitle:"An independent apartment for up to 4 guests", suiteText:"VALF Suite is a welcoming, independent apartment designed to offer comfort and freedom throughout your stay.", servicesTitle:"Everything you need for a comfortable stay", galleryTitle:"A look inside the apartment", galleryText:"Final photographs of the interiors and outdoor area will be published soon. Contact us in the meantime for more information.", areaTitle:"Explore the surrounding area", areaText:"The sea, historic villages and art cities can be reached by car or public transport. Arcola station is on the Genoa–Pisa line; La Spezia Centrale is the gateway to the Cinque Terre Express.", bookTitle:"Request availability", bookText:"Select your dates and send a request. Angela will reply personally with availability and conditions.", contactsTitle:"Contact", contactsText:"We are available for information and stay requests.", termsTitle:"Booking and cancellation terms", send:"Send request", privacy:"I agree to the processing of my data for this request." },
  fr: { nav:["La Suite","Services","Galerie","Les environs","Réserver","Contact"], hero:"Votre pied-à-terre entre la Ligurie et la Toscane", heroText:"VALF Suite est un appartement indépendant de plain-pied à Arcola, avec parking privé, Wi‑Fi et climatisation. Un point de départ pratique pour découvrir Lerici, Portovenere, les Cinque Terre, Sarzana et la côte toscane.", discover:"Découvrir la Suite", availability:"Vérifier les disponibilités", welcome:"Le plaisir d’un espace rien que pour vous", welcomeText:"Des espaces soignés et accueillants, pensés pour les voyageurs qui recherchent calme, indépendance et une situation pratique entre mer et villages.", strategic:"Une position stratégique entre mer et villages", suiteTitle:"Un appartement indépendant jusqu’à 4 personnes", suiteText:"VALF Suite est un appartement accueillant et indépendant, conçu pour offrir confort et liberté pendant votre séjour.", servicesTitle:"Tout le nécessaire pour un séjour confortable", galleryTitle:"Un aperçu de l’appartement", galleryText:"Les photos définitives des intérieurs et de l’espace extérieur seront bientôt publiées. Contactez-nous pour plus d’informations.", areaTitle:"Découvrir les environs", areaText:"Mer, villages historiques et villes d’art sont accessibles en voiture ou en transports publics. La gare d’Arcola se trouve sur la ligne Gênes–Pise; La Spezia Centrale dessert les Cinque Terre.", bookTitle:"Demander les disponibilités", bookText:"Sélectionnez vos dates et envoyez une demande. Angela vous répondra personnellement.", contactsTitle:"Contact", contactsText:"Nous sommes à votre disposition pour toute information.", termsTitle:"Conditions de réservation et d’annulation", send:"Envoyer la demande", privacy:"J’accepte le traitement de mes données pour cette demande." },
  es: { nav:["La Suite","Servicios","Galería","Alrededores","Reservar","Contacto"], hero:"Tu alojamiento entre Liguria y Toscana", heroText:"VALF Suite es un apartamento independiente en planta baja en Arcola, con aparcamiento privado, Wi‑Fi y climatización. Una base cómoda para descubrir Lerici, Portovenere, Cinque Terre, Sarzana y la costa toscana.", discover:"Descubre la Suite", availability:"Consultar disponibilidad", welcome:"El placer de un espacio solo para vosotros", welcomeText:"Espacios cuidados y acogedores, pensados para quienes buscan tranquilidad, independencia y una ubicación cómoda entre el mar y los pueblos.", strategic:"Una ubicación estratégica entre mar y pueblos", suiteTitle:"Un apartamento independiente para hasta 4 huéspedes", suiteText:"VALF Suite es un apartamento acogedor e independiente, pensado para ofrecer comodidad y libertad durante la estancia.", servicesTitle:"Todo lo necesario para una estancia cómoda", galleryTitle:"Una mirada al apartamento", galleryText:"Pronto publicaremos las fotografías definitivas del interior y de la zona exterior. Contáctanos para más información.", areaTitle:"Qué ver en los alrededores", areaText:"El mar, los pueblos históricos y las ciudades de arte son accesibles en coche o transporte público. La estación de Arcola está en la línea Génova–Pisa; La Spezia Centrale conecta con Cinque Terre.", bookTitle:"Solicitar disponibilidad", bookText:"Selecciona las fechas y envía una solicitud. Angela responderá personalmente.", contactsTitle:"Contacto", contactsText:"Estamos disponibles para información y solicitudes.", termsTitle:"Condiciones de reserva y cancelación", send:"Enviar solicitud", privacy:"Acepto el tratamiento de mis datos para esta solicitud." },
  de: { nav:["Die Suite","Ausstattung","Galerie","Umgebung","Buchen","Kontakt"], hero:"Ihr Rückzugsort zwischen Ligurien und der Toskana", heroText:"VALF Suite ist ein unabhängiges Apartment im Erdgeschoss in Arcola, mit Privatparkplatz, WLAN und Klimaanlage. Ein bequemer Ausgangspunkt für Lerici, Portovenere, Cinque Terre, Sarzana und die toskanische Küste.", discover:"Die Suite entdecken", availability:"Verfügbarkeit prüfen", welcome:"Ein Ort ganz für Sie", welcomeText:"Gepflegte, einladende Räume für Gäste, die Ruhe, Unabhängigkeit und eine günstige Lage zwischen Küste und historischen Dörfern suchen.", strategic:"Strategisch gelegen zwischen Meer und Dörfern", suiteTitle:"Ein unabhängiges Apartment für bis zu 4 Gäste", suiteText:"VALF Suite ist ein einladendes, unabhängiges Apartment, das Komfort und Freiheit während Ihres Aufenthalts bietet.", servicesTitle:"Alles für einen komfortablen Aufenthalt", galleryTitle:"Ein Blick ins Apartment", galleryText:"Die endgültigen Fotos der Innenräume und des Außenbereichs werden bald veröffentlicht. Kontaktieren Sie uns für weitere Informationen.", areaTitle:"Die Umgebung entdecken", areaText:"Meer, historische Dörfer und Kunststädte sind mit Auto oder öffentlichen Verkehrsmitteln erreichbar. Der Bahnhof Arcola liegt an der Strecke Genua–Pisa; La Spezia Centrale ist der Ausgangspunkt für Cinque Terre.", bookTitle:"Verfügbarkeit anfragen", bookText:"Wählen Sie Ihre Daten und senden Sie eine Anfrage. Angela antwortet Ihnen persönlich.", contactsTitle:"Kontakt", contactsText:"Für Informationen und Aufenthaltsanfragen sind wir gerne da.", termsTitle:"Buchungs- und Stornierungsbedingungen", send:"Anfrage senden", privacy:"Ich stimme der Verarbeitung meiner Daten für diese Anfrage zu." }
} satisfies Record<Lang, Record<string, string | string[]>>;

const routes = ["la-suite","servizi","galleria","dintorni","prenota","contatti"];
const suitePhotos=["/images/valf-suite/_DSC4773.jpg","/images/valf-suite/_DSC4776.jpg","/images/valf-suite/_DSC4779.jpg","/images/valf-suite/_DSC4782.jpg","/images/valf-suite/_DSC4786.jpg","/images/valf-suite/_DSC4789.jpg","/images/valf-suite/_DSC4791.jpg","/images/valf-suite/_DSC4803.jpg","/images/valf-suite/_DSC4816.jpg","/images/valf-suite/_DSC5885.jpg","/images/valf-suite/_DSC5888.jpg"];
const galleryControls:Record<Lang,{previous:string;next:string;select:string;counter:string}>={
  it:{previous:"Foto precedente",next:"Foto successiva",select:"Mostra la foto",counter:"Foto"},
  en:{previous:"Previous photo",next:"Next photo",select:"Show photo",counter:"Photo"},
  fr:{previous:"Photo précédente",next:"Photo suivante",select:"Afficher la photo",counter:"Photo"},
  es:{previous:"Foto anterior",next:"Foto siguiente",select:"Mostrar la foto",counter:"Foto"},
  de:{previous:"Vorheriges Foto",next:"Nächstes Foto",select:"Foto anzeigen",counter:"Foto"},
};
const reservedAreaLabels: Record<Lang,string> = { it:"Area riservata", en:"Reserved area", fr:"Espace réservé", es:"Área reservada", de:"Geschützter Bereich" };
const guestGuideLabels: Record<Lang,string> = { it:"Guida ospiti", en:"Guest guide", fr:"Guide d’accueil", es:"Guía para huéspedes", de:"Gästehandbuch" };
const guestGuideUrls: Record<Lang,string> = {
  it:"/documenti/VALF_Suite_Guida_Ospiti_IT.pdf",
  en:"/documenti/VALF_Suite_Guida_Ospiti_EN.pdf",
  fr:"/documenti/VALF_Suite_Guida_Ospiti_FR.pdf",
  es:"/documenti/VALF_Suite_Guida_Ospiti_ES.pdf",
  de:"/documenti/VALF_Suite_Guida_Ospiti_DE.pdf",
};
const privateAreaUrl="https://valfsuite.valfservice.it/area-riservata";
const whatsappUrl="https://wa.me/393403726198";
const homeHeroPhoto="/images/valf-suite/_DSC4803.jpg";
const homeCommercial:Record<Lang,{eyebrow:string;whatsapp:string;keyFacts:string[];features:string[]}> = {
  it:{eyebrow:"Appartamento ad uso turistico · Arcola (SP)",whatsapp:"Scrivici su WhatsApp",keyFacts:["Ingresso indipendente","Parcheggio privato","Piano terra","Posizione strategica per Golfo dei Poeti e Cinque Terre"],features:["Ingresso indipendente","Parcheggio privato","Wi‑Fi","Climatizzazione","Fino a 4 ospiti"]},
  en:{eyebrow:"Independent tourist apartment · Arcola (SP)",whatsapp:"Message us on WhatsApp",keyFacts:["Private entrance","Private parking","Ground floor","Strategic location for the Gulf of Poets and Cinque Terre"],features:["Private entrance","Private parking","Wi‑Fi","Air conditioning","Up to 4 guests"]},
  fr:{eyebrow:"Appartement indépendant · Arcola (SP)",whatsapp:"Écrivez-nous sur WhatsApp",keyFacts:["Entrée indépendante","Parking privé","Rez-de-chaussée","Situation stratégique pour le Golfe des Poètes et les Cinque Terre"],features:["Entrée indépendante","Parking privé","Wi‑Fi","Climatisation","Jusqu’à 4 personnes"]},
  es:{eyebrow:"Apartamento independiente · Arcola (SP)",whatsapp:"Escríbenos por WhatsApp",keyFacts:["Entrada independiente","Aparcamiento privado","Planta baja","Ubicación estratégica para el Golfo de los Poetas y Cinque Terre"],features:["Entrada independiente","Aparcamiento privado","Wi‑Fi","Climatización","Hasta 4 huéspedes"]},
  de:{eyebrow:"Unabhängiges Apartment · Arcola (SP)",whatsapp:"Schreiben Sie uns auf WhatsApp",keyFacts:["Eigener Eingang","Privatparkplatz","Erdgeschoss","Strategische Lage für den Golf der Poeten und Cinque Terre"],features:["Eigener Eingang","Privatparkplatz","WLAN","Klimaanlage","Bis zu 4 Gäste"]},
};
const suiteStory:Record<Lang,string[]> = {
  it:[
    "VALF Suite è un appartamento accogliente e indipendente, pensato per offrire comfort e libertà durante il soggiorno.",
    "La zona giorno dispone di una cucina completa e completamente attrezzata, con tutto il necessario per preparare colazioni, pranzi e cene in piena autonomia.",
    "La zona notte comprende una camera matrimoniale aperta, ben definita rispetto al resto dell’ambiente. Nella zona giorno è presente anche un divano letto da una piazza e mezzo.",
    "Completa gli spazi un caratteristico soppalco con letto matrimoniale, raccolto e intimo, con altezza ridotta.",
    "Il bagno, moderno e curato, è dotato di un’ampia doccia.",
    "Situata al piano terra, VALF Suite dispone di ingresso indipendente e può accogliere fino a 4 ospiti.",
  ],
  en:[
    "VALF Suite is a welcoming, independent apartment designed to offer comfort and freedom throughout your stay.",
    "The living area has a complete, fully equipped kitchen with everything needed to prepare breakfast, lunch and dinner independently.",
    "The sleeping area includes an open double bedroom, clearly defined from the rest of the space. The living area also has a small double sofa bed.",
    "A distinctive mezzanine with a double bed completes the accommodation: cosy and intimate, with reduced headroom.",
    "The modern, carefully finished bathroom has a large shower.",
    "Located on the ground floor, VALF Suite has a private entrance and accommodates up to 4 guests.",
  ],
  fr:[
    "VALF Suite est un appartement accueillant et indépendant, pensé pour offrir confort et liberté pendant votre séjour.",
    "L’espace de vie dispose d’une cuisine complète et entièrement équipée, avec tout le nécessaire pour préparer petits-déjeuners, déjeuners et dîners en toute autonomie.",
    "L’espace nuit comprend une chambre double ouverte, bien délimitée du reste de la pièce. Le séjour dispose également d’un canapé-lit d’une place et demie.",
    "Une mezzanine de caractère avec lit double complète les espaces : intime et chaleureuse, avec une hauteur réduite.",
    "La salle de bains moderne et soignée est équipée d’une grande douche.",
    "Située au rez-de-chaussée, VALF Suite dispose d’une entrée indépendante et peut accueillir jusqu’à 4 personnes.",
  ],
  es:[
    "VALF Suite es un apartamento acogedor e independiente, pensado para ofrecer comodidad y libertad durante la estancia.",
    "La zona de día dispone de una cocina completa y totalmente equipada, con todo lo necesario para preparar desayunos, comidas y cenas con total autonomía.",
    "La zona de noche incluye un dormitorio doble abierto, bien definido con respecto al resto del ambiente. En la zona de día también hay un sofá cama de plaza y media.",
    "Completa el espacio un característico altillo con cama doble, acogedor e íntimo, de altura reducida.",
    "El baño, moderno y cuidado, dispone de una amplia ducha.",
    "Situada en la planta baja, VALF Suite tiene entrada independiente y puede alojar hasta 4 huéspedes.",
  ],
  de:[
    "VALF Suite ist ein einladendes, unabhängiges Apartment, das Komfort und Freiheit während Ihres Aufenthalts bietet.",
    "Der Wohnbereich verfügt über eine vollständige und komplett ausgestattete Küche mit allem, was Sie für Frühstück, Mittag- und Abendessen benötigen.",
    "Der Schlafbereich umfasst ein offenes Doppelzimmer, das klar vom übrigen Raum abgegrenzt ist. Im Wohnbereich befindet sich außerdem ein kleines Doppelschlafsofa.",
    "Eine charakteristische Galerie mit Doppelbett ergänzt die Räume: gemütlich und intim, mit niedriger Deckenhöhe.",
    "Das moderne, gepflegte Bad ist mit einer großen Dusche ausgestattet.",
    "VALF Suite liegt im Erdgeschoss, hat einen eigenen Eingang und bietet Platz für bis zu 4 Gäste.",
  ],
};
const serviceItems:Record<Lang,string[]> = {
  it:["Wi‑Fi gratuito","Climatizzatore caldo/freddo","Angolo cottura attrezzato","TV","Parcheggio privato","Area esterna privata","Piano terra","Biancheria e asciugamani inclusi"],
  en:["Free Wi‑Fi","Heating and air conditioning","Equipped kitchenette","TV","Private parking","Private outdoor area","Ground floor","Bed linen and towels included"],
  fr:["Wi‑Fi gratuit","Climatisation chaud/froid","Kitchenette équipée","Télévision","Parking privé","Espace extérieur privé","Rez-de-chaussée","Linge de lit et serviettes inclus"],
  es:["Wi‑Fi gratuito","Climatización frío/calor","Cocina equipada","Televisión","Aparcamiento privado","Zona exterior privada","Planta baja","Ropa de cama y toallas incluidas"],
  de:["Kostenloses WLAN","Klimaanlage warm/kalt","Ausgestattete Küchenzeile","TV","Privatparkplatz","Privater Außenbereich","Erdgeschoss","Bettwäsche und Handtücher inklusive"]
};
const places = [
  ["Cinque Terre","40 min in auto · consigliato il treno da La Spezia","5-terre.webp"],
  ["Lerici e San Terenzo","20 min · castello, spiagge e Golfo dei Poeti","lerici.webp"],
  ["Tellaro","25 min · borgo di pescatori sul mare","tellaro.webp"],
  ["Portovenere","30 min · San Pietro e isola Palmaria","portovenere.webp"],
  ["Sarzana","10–15 min · centro storico e fortezze","Sarzana.webp"],
  ["Lunigiana","20–40 min · castelli, borghi e natura","stretti-di-giaredo-3.webp"],
  ["Viareggio e Versilia","45 min · spiagge e architettura liberty","versilia.webp"],
  ["Pisa","circa 1 ora · Piazza dei Miracoli","pisa.webp"]
];
const labels:Record<Lang,{contact:string[];form:string[];notice:string;details:string[];terms:[string,string][]}> = {
  it:{contact:["Referente","Telefono e WhatsApp","Email","Indirizzo"],form:["Arrivo","Partenza","Ospiti","Nome","Email","Messaggio"],notice:"Capienza massima: 4 ospiti · Non sono ammessi animali · Non è consentito fumare all’interno.",details:["Fino a 4 ospiti","Appartamento indipendente al piano terra","Camera matrimoniale aperta e divano letto","Soppalco con letto matrimoniale e altezza ridotta","Cucina completa e completamente attrezzata","Area esterna e parcheggio privato"],terms:[["Prenotazione e pagamento","La prenotazione si conferma con un acconto del 30%. Il saldo è dovuto 7 giorni prima dell’arrivo."],["Cancellazione","Rimborso completo fino a 7 giorni prima dell’arrivo. Oltre tale termine l’importo versato non è rimborsabile."],["Check-in e check-out","Gli orari sono flessibili e concordati direttamente con gli ospiti."],["Regole della casa","Massimo 4 ospiti. Non sono ammessi animali, fumo all’interno, feste o eventi."]]},
  en:{contact:["Contact person","Phone and WhatsApp","Email","Address"],form:["Arrival","Departure","Guests","Name","Email","Message"],notice:"Maximum 4 guests · No pets · No smoking indoors.",details:["Up to 4 guests","Independent ground-floor apartment","Open double bedroom and sofa bed","Mezzanine with double bed and reduced headroom","Complete, fully equipped kitchen","Private outdoor area and parking"],terms:[["Booking and payment","A 30% deposit confirms the booking. The balance is due 7 days before arrival."],["Cancellation","Full refund up to 7 days before arrival. After that date, payments are non-refundable."],["Check-in and check-out","Times are flexible and agreed directly with guests."],["House rules","Maximum 4 guests. No pets, indoor smoking, parties or events."]]},
  fr:{contact:["Contact","Téléphone et WhatsApp","E-mail","Adresse"],form:["Arrivée","Départ","Personnes","Nom","E-mail","Message"],notice:"Maximum 4 personnes · Animaux non admis · Il est interdit de fumer à l’intérieur.",details:["Jusqu’à 4 personnes","Appartement indépendant au rez-de-chaussée","Chambre double ouverte et canapé-lit","Mezzanine avec lit double et hauteur réduite","Cuisine complète et entièrement équipée","Espace extérieur privé et parking"],terms:[["Réservation et paiement","La réservation est confirmée par un acompte de 30 %. Le solde est dû 7 jours avant l’arrivée."],["Annulation","Remboursement intégral jusqu’à 7 jours avant l’arrivée. Ensuite, les sommes versées ne sont pas remboursables."],["Arrivée et départ","Les horaires sont flexibles et convenus directement avec les hôtes."],["Règles de la maison","Maximum 4 personnes. Animaux, tabac à l’intérieur, fêtes et événements interdits."]]},
  es:{contact:["Persona de contacto","Teléfono y WhatsApp","Correo electrónico","Dirección"],form:["Llegada","Salida","Huéspedes","Nombre","Correo electrónico","Mensaje"],notice:"Máximo 4 huéspedes · No se admiten animales · No se permite fumar en el interior.",details:["Hasta 4 huéspedes","Apartamento independiente en planta baja","Dormitorio doble abierto y sofá cama","Altillo con cama doble y altura reducida","Cocina completa y totalmente equipada","Zona exterior privada y aparcamiento"],terms:[["Reserva y pago","La reserva se confirma con un depósito del 30 %. El saldo se abona 7 días antes de la llegada."],["Cancelación","Reembolso completo hasta 7 días antes de la llegada. Después, los importes abonados no son reembolsables."],["Llegada y salida","Los horarios son flexibles y se acuerdan directamente con los huéspedes."],["Normas de la casa","Máximo 4 huéspedes. No se admiten animales, tabaco en el interior, fiestas ni eventos."]]},
  de:{contact:["Ansprechpartnerin","Telefon und WhatsApp","E-Mail","Adresse"],form:["Anreise","Abreise","Gäste","Name","E-Mail","Nachricht"],notice:"Maximal 4 Gäste · Keine Haustiere · Rauchen im Innenbereich nicht gestattet.",details:["Bis zu 4 Gäste","Unabhängiges Apartment im Erdgeschoss","Offenes Doppelzimmer und Schlafsofa","Galerie mit Doppelbett und niedriger Deckenhöhe","Vollständig ausgestattete Küche","Privater Außenbereich und Parkplatz"],terms:[["Buchung und Zahlung","Die Buchung wird mit einer Anzahlung von 30 % bestätigt. Der Restbetrag ist 7 Tage vor Anreise fällig."],["Stornierung","Volle Erstattung bis 7 Tage vor Anreise. Danach sind Zahlungen nicht erstattungsfähig."],["Check-in und Check-out","Die Zeiten sind flexibel und werden direkt mit den Gästen vereinbart."],["Hausregeln","Maximal 4 Gäste. Keine Haustiere, Rauchen im Innenbereich, Partys oder Veranstaltungen."]]}
};

export function SitePage({ lang: langValue, page }: { lang: string; page: string }) {
  const lang = (langValue in copy ? langValue : "it") as Lang;
  const t = copy[lang];
  const [open,setOpen] = useState(false); const [status,setStatus] = useState(""); const [gallerySlide,setGallerySlide]=useState(0);
  const base = lang === "it" ? "" : `/${lang}`;
  const href = (route:string) => `${base}/${route}`;
  async function submit(e:FormEvent<HTMLFormElement>){ e.preventDefault(); setStatus("…"); const f=e.currentTarget; const payload={...Object.fromEntries(new FormData(f)),lingua:lang}; const r=await fetch("/api/disponibilita",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const j=await r.json().catch(()=>({})); setStatus(r.ok?`✓ ${j.message||"Richiesta ricevuta"}`:(j.message||"Invio non disponibile")); if(r.ok)f.reset(); }
  return <main className={page==="galleria"?"gallery-layout":undefined}>
    <header className="site-header"><a className="brand" href={base||"/"}><img src="/logo-valf-suite.png" alt="VALF Suite"/></a><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}><span className="sr-only">Menu</span><span/><span/></button><nav className={open?"nav open":"nav"}>{routes.map((r,i)=><a key={r} className={r==="prenota"?"nav-cta":""} href={href(r)}>{(t.nav as string[])[i]}</a>)}</nav></header>
    <div className="language-bar" aria-label="Lingue">{(["it","en","fr","es","de"] as Lang[]).map(l=><a key={l} className={l===lang?"active":""} aria-current={l===lang?"page":undefined} href={l==="it"?`/${page==="home"?"":page}`:`/${l}/${page==="home"?"":page}`}>{l.toUpperCase()}</a>)}</div>
    {page==="home" && <><section className="hero"><div className="hero-copy"><p className="eyebrow">{homeCommercial[lang].eyebrow}</p><h1>{t.hero as string}</h1><p className="hero-keyfacts">{homeCommercial[lang].keyFacts.join(" · ")}</p><p className="lead">{t.heroText as string}</p><div className="hero-features" aria-label="Caratteristiche principali">{homeCommercial[lang].features.map(feature=><span key={feature}>{feature}</span>)}</div><div className="hero-actions"><a className="button" href={href("prenota")}>{t.availability as string}</a><a className="button button-whatsapp" href={whatsappUrl} target="_blank" rel="noreferrer">{homeCommercial[lang].whatsapp}</a></div></div><figure className="hero-art"><img src={homeHeroPhoto} alt="Cucina, tavolo e scala del soppalco di VALF Suite" fetchPriority="high"/><figcaption>VALF Suite · Arcola</figcaption></figure></section><section className="intro section"><div><p className="eyebrow">VALF Suite</p><h2>{t.welcome as string}</h2></div><div className="intro-text"><p>{t.welcomeText as string}</p></div></section><section className="services section"><div className="section-heading"><p className="eyebrow">Liguria & Toscana</p><h2>{t.strategic as string}</h2></div><div className="destination-grid home-destinations">{places.slice(0,6).map(([p,d])=><article key={p}><h3>{p}</h3><p>{d}</p></article>)}</div></section><section className="home-links">{routes.slice(0,4).map((r,i)=><a key={r} href={href(r)}><strong>{(t.nav as string[])[i]}</strong><b>→</b></a>)}</section></>}
    {page==="la-suite" && <Info title={t.suiteTitle as string} eyebrow={(t.nav as string[])[0]} intro=""><div className="suite-story">{suiteStory[lang].map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div><ul className="detail-list">{labels[lang].details.map(x=><li key={x}>{x}</li>)}</ul></Info>}
    {page==="servizi" && <Info title={t.servicesTitle as string} eyebrow={(t.nav as string[])[1]} intro=""><div className="amenities">{serviceItems[lang].map(s=><article key={s}><h3>{s}</h3></article>)}</div><p className="notice">{labels[lang].notice}</p></Info>}
    {page==="galleria" && <GalleryPage lang={lang} title={t.galleryTitle as string} current={gallerySlide} onSelect={setGallerySlide}/>}
    {page==="dintorni" && <Info title={t.areaTitle as string} eyebrow={(t.nav as string[])[3]} intro={t.areaText as string}><div className="places-list">{places.map(([p,d,img])=><article key={p}><img src={`/dintorni/${img}`} alt={p}/><div><h3>{p}</h3><p>{d}</p></div></article>)}</div></Info>}
    {page==="prenota" && <Info title={t.bookTitle as string} eyebrow={(t.nav as string[])[4]} intro={t.bookText as string}><Availability onSubmit={submit} t={t} status={status} labels={labels[lang].form}/></Info>}
    {page==="contatti" && <Info title={t.contactsTitle as string} eyebrow={(t.nav as string[])[5]} intro={t.contactsText as string}><div className="contact-card"><p><small>{labels[lang].contact[0]}</small><strong>Angela</strong></p><p><small>{labels[lang].contact[1]}</small><a className="contact-link" href="tel:+393403726198">+39 340 372 6198</a></p><p><small>{labels[lang].contact[2]}</small><a className="contact-link" href="mailto:valfsuite@gmail.com">valfsuite@gmail.com</a></p><p><small>{labels[lang].contact[3]}</small><span>Via Aurelia Nord 97, 19021 Arcola (SP)</span></p></div></Info>}
    {page==="condizioni" && <Info title={t.termsTitle as string} eyebrow="VALF Suite" intro=""><div className="terms">{labels[lang].terms.map(([h,p])=><section key={h}><h3>{h}</h3><p>{p}</p></section>)}</div></Info>}
    <footer><a className="brand footer-brand" href={base||"/"}><img src="/logo-valf-suite.png" alt="VALF Suite"/></a><p className="footer-location">Via Aurelia Nord 97 · Arcola (SP)<span>CIN IT011002C2FW233HQM · CITRA 011002-LT-0278</span></p><div><a href={guestGuideUrls[lang]} target="_blank" rel="noreferrer">{guestGuideLabels[lang]}</a><a href={href("condizioni")}>{t.termsTitle as string}</a><a href={href("contatti")}>{t.contactsTitle as string}</a><a href={privateAreaUrl} rel="nofollow">{reservedAreaLabels[lang]}</a></div><small>© {new Date().getFullYear()} VALF Suite</small></footer>
  </main>
}

function Info({title,eyebrow,intro,children}:{title:string;eyebrow:string;intro:string;children:React.ReactNode}){return <><section className="page-hero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{intro&&<p className="lead">{intro}</p>}</section><section className="page-body">{children}</section></>}
function GalleryPage({lang,title,current,onSelect}:{lang:Lang;title:string;current:number;onSelect:(index:number)=>void}){return <section className="gallery-page"><header className="gallery-heading"><p className="eyebrow">{(copy[lang].nav as string[])[2]}</p><h1>{title}</h1></header><GallerySlider lang={lang} current={current} onSelect={onSelect}/></section>}
function GallerySlider({lang,current,onSelect}:{lang:Lang;current:number;onSelect:(index:number)=>void}){const controls=galleryControls[lang];const move=(direction:number)=>onSelect((current+direction+suitePhotos.length)%suitePhotos.length);return <section className="gallery-slider" aria-label={copy[lang].galleryTitle as string} tabIndex={0} onKeyDown={event=>{if(event.key==="ArrowLeft"){event.preventDefault();move(-1);}if(event.key==="ArrowRight"){event.preventDefault();move(1);}}}><div className="gallery-stage"><figure><img key={suitePhotos[current]} src={suitePhotos[current]} alt={`VALF Suite ad Arcola · foto ${current+1}`}/><figcaption>{controls.counter} {current+1} / {suitePhotos.length}</figcaption></figure><button type="button" className="gallery-arrow previous" aria-label={controls.previous} onClick={()=>move(-1)}>←</button><button type="button" className="gallery-arrow next" aria-label={controls.next} onClick={()=>move(1)}>→</button></div><div className="gallery-thumbnails" aria-label={controls.select}>{suitePhotos.map((src,index)=><button type="button" key={src} className={index===current?"active":""} aria-label={`${controls.select} ${index+1}`} aria-current={index===current?"true":undefined} onClick={()=>onSelect(index)}><img src={src} alt="" loading="lazy"/></button>)}</div></section>}
function Availability({onSubmit,t,status,labels:l}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;t:Record<string,string|string[]>;status:string;labels:string[]}){const today=localIsoDate(new Date());return <form className="availability-form" onSubmit={onSubmit}><div className="form-row"><label>{l[0]}<input name="arrivo" type="date" min={today} required/></label><label>{l[1]}<input name="partenza" type="date" min={today} required/></label></div><div className="form-row"><label>{l[2]}<select name="ospiti" required defaultValue=""><option value="" disabled>—</option>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label><label>{l[3]}<input name="nome" maxLength={120} required/></label></div><label>{l[4]}<input name="email" type="email" maxLength={254} required/></label><label>{l[5]}<textarea name="messaggio" maxLength={2000} rows={4}/></label><label className="form-trap" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="privacy"><input name="privacy" type="checkbox" required/><span>{t.privacy as string}</span></label><button className="button submit">{t.send as string}</button><p className="form-status" role="status">{status}</p></form>}

function localIsoDate(date:Date){const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,"0");const d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`;}
